blank_issues_enabled: false
# contact_links:
#   - name: Submit a Bug Report
#     url: https://github.com/taha-abbasi/pizza-pet-cemetery/issues/new?template=bug_report.md
#     about: Report bugs or issues in the game.
#   - name: Suggest a Feature
#     url: https://github.com/taha-abbasi/pizza-pet-cemetery/issues/new?template=feature_request.md
#     about: Share ideas for new features or improvements.
  - name: Share a Pizza Pet Idea
    url: https://github.com/taha-abbasi/pizza-pet-cemetery/issues/new?template=pizza_pet_cemetery_idea.md
    about: Submit creative ideas for Pizza Pets and related games.