blank_issues_enabled: false
contact_links:
  - name: Share a Pizza Pet Idea
    url: https://github.com/taha-abbasi/pizza-pet-cemetery/issues/new?template=pizza_pet_cemetery_idea.md
    about: Submit creative ideas for Pizza Pets and related games.